[versions]
agp = "8.4.0-alpha11"
kotlin = "1.9.0"
coreKtx = "1.10.1"
fragmentKtx = "1.6.2"
lifecycleRuntimeKtx = "2.6.1"
lifecycleLivedataKtx = "2.7.0"
gson = "2.10.1"
koin = "3.5.6"
databindingRuntime = "8.3.2"

[libraries]
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
androidx-databinding-runtime = { group = "androidx.databinding", name = "databinding-runtime", version.ref = "databindingRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

